browser=edge

url=https://qa.instulearn.com/
timeout=10
googleUrl=https://www.google.com/


instuLearnUrl=https://qa.instulearn.com/

emailRamazan="ramazan.student@instulearn.com"
passWordRamazan="Learn.1406"

emailNihad="nihad.student@instulearn.com"
passwordnihad="Learn.1406"

melihOrganization="rilirip378@protonza.com"
melihPassOrg="Learn.1406"
melihStudent="melih.student@instulearn.com


gecerliEmail=cennet.student@instulearn.com
gecerliFullName=cennet
gecerliPassword=Learn.1406
gecerliRetypePassword=Learn.1406



team2StudentEmail_Yusuf=yusuf.student@instulearn.com
team2Password_Yusuf=Learn.1406
team2InstructorEmail_Yusuf=yusuf.teacher@instulearn.com
loginPageUrl_Yusuf=https://qa.instulearn.com/login
Filtercertificatesfrom_Yusuf:2025-09-01
Filtercertificatesfrom_to:2025-09-29
CertificateID:4568754
Captcha_yusuf:45615665
expectedUrlStudents_Yusuf=https://qa.instulearn.com/panel/manage/students
expectedUrlStudentsNew_Yusuf=https://qa.instulearn.com/panel/manage/students/new
forgetPasswordPageUrl_Yusuf=https://qa.instulearn.com/forget-password



loginPageUrl=https://qa.instulearn.com/login
registerPageUrl=https://qa.instulearn.com/register
forgetPasswordPageUrl=https://qa.instulearn.com/forget-password